### ISSUE TITLE
Braindump of issues

### ISSUE THREAD

**Issue by davmac314** [stivale/stivale#20]
Hi,
Having just implemented a stivale 2 loader (https://github.com/davmac314/tosaithe), I wanted to do a braindump of things I came across while they're still fresh in my mind. These are just my thoughts and sometimes just opinion so feel free to close the issue without addressing anything, or ask me to open separate issues for individual things.

First, the positives: the protocol is simple and flexible such that from a kernel author perspective, it is great; it really makes it much easier to get a kernel off the ground. The tag system for extensibility works pretty well for requesting particular features.

Now, a bunch of thoughts/issues/wishes (sorry - this really turned into a huge dump of things):

### General information

> For relocatable kernels, the bootloader may change the load addresses of the sections by adding a slide, if the specified location of a segment is not available for use

- What is the granularity of the slide?
- (Ideally, there would be some way to limit the granularity, eg allow sliding by only 2MB increments, since a kernel may be designed to use a certain page size and may want to keep itself page-aligned).

### Address mappings

The document says (just taking a slice for example):

```
  0x0000000000000000   - 4 GiB plus any additional memory map entry -> 0xffff800000000000 (4-level paging only)
  0x0000000000000000   - 4 GiB plus any additional memory map entry -> 0xff00000000000000 (5-level paging only)
```

1. I personally think this is the wrong way around; linear addresses map to physical. The way it's shown currently, there are (conflicting) physical-to-linear mappings instead. (This is just a niggle).
2. What does "plus any additional memory map entry" mean? If it means that any entries in the memory map will be mapped, why have a special case for the first 4GiB?
3. The missing mapping (0x0000000000000000  > 0xffffffff80000000) when PMRs are enabled is odd. If I want to make my read-only section read-only, I also lose the automatic mapping of the first 2GB of address space, which is often a nice mapping to have. What's the rationale?

### Other kernel entry notes

1. GDT: Why include 16-bit code/data segment? These are useless.
2. GDT: There is no such thing as a "64-bit data descriptor". I assume this should just be a another 32-bit data descriptor, though you could also get by without it entirely (64-bit code can just use the "32-bit" data descriptor just fine).
3. GDT (IA-32): includes 64-bit code/data segment, which precludes use on hardware which is 32-bit only?
4. "rsp is set to the requested stack as per stivale2 header. If the requested value is non-null, an invalid return address of 0 is pushed ..." -- why push an invalid return address only if the requested value is non-null? Is the kernel expected to be able to return to the bootloader if it doesn't supply a stack pointer value?
5. Are EFI boot services still available on entry to the kernel, or has ExitBootServices already been called?

### Stivale2 header

> The kernel executable shall have a section .stivale2hdr which will contain, or an anchor pointing to, the header that the bootloader will parse."

This is grammatically bad, but I think this is probably meant to say: "The kernel executable shall have a section .stivale2hdr which will contain, or **will contain** an anchor pointing to, the header that the bootloader will parse."

However, allowing either the header or an anchor to it seems an odd choice which just complicates the implementation for no benefit.

1. If there is an anchor, is it the same format as the `stivale2_anchor`? If so, should the other entries be used by the bootloader or ignored? What if they conflict with the ELF header?
2. In the header, how should the bootloader treat set flags that it does not recognize? It might be worth splitting the flags into (0-31: flags that can be safely ignored; 32-63: flags that if set but not understood should cause refusal to boot the kernel).

### PMRs

> Only 64-bit, higher half, ELF (non anchored) kernels can take advantage of this feature. Requesting this feature for 32-bit, lower half, or non-ELF kernels has undefined behaviour.

1. disallowing PMRs for 32-bit ELF kernels seems odd - what is the rationale? (without a written rationale, it feels a lot like the reason is just that you didn't implement it in Limine? - but that shouldn't be reason for disallowing it in the spec).
2. even if it is not allowed, "requesting this feature ... has undefined behaviour" seems to be going way too far. The behaviour should be to refuse to boot, or to boot without providing the feature, surely; either of those could be mandated, or the option could be left open for either possibility.

### Header tags

> The stivale2 header uses a mechanism to avoid having protocol versioning, but rather, feature-specific support detection.

Ok, but, for the framebuffer tag:

> If used alone, without "any video" header tag, this tag mandates a graphical linear framebuffer and the bootloader will refuse to boot the kernel if it fails to initialise a framebuffer.

Why refuse to boot due to the presence of a tag, when a less-featured bootloader that doesn't even recognize the tag would happily still boot the kernel (albeit without a framebuffer)?

In general the issue is, I think, that there is no way to specify a tag which the bootloader _must_ respect. Currently all tags are "if the bootloader supports it" (except maybe for the framebuffer tag, as per above).

Thoughts on how to solve this include:

- introduce a second list of tags in the header, presence indicated by a flag. These would be mandatory tags, i.e. if the bootloader doesn't recognize any of them or does not support them then it should refuse to boot the kernel.
- or, keep all tags in the one list, and have a special tag which contains a list of the tag identifiers for mandatory tags. I'd suggest requiring that the special tag be the first tag in the list, as it will simplify implementation.

Terminal tag:
> This service is not provided to IA-32 kernels.

- again, why not? There doesn't seem to be any good reason to disallow it in the spec, even if the flagship implementation doesn't support it.

High memory mapping tag:

- given that physical memory should be mapped at either 0xff00000000000000 or 0xffff800000000000, should this always contain one of those values? Or have I misunderstood the mapping requirements?

### General thoughts

There is no rationale for a lot of restrictions/statements in the spec; providing rationale is often helpful for understanding and might have rendered evident answers to a lot of the above questions.

That's all - I hope this dump is useful and not just an annoyance.

**Comment by mintsuki** [comment]
Hello, and thanks for expressing your thoughts about the protocol.

I will proceed replying to these points, one by one, to the best of my abilities.

== General information ==
1. The granularity of the slide will not result in a base address with smaller alignment than the greatest alignment of any of the ELF file segments. This will be specified in the specification in an upcoming commit (from now on marked as "will address").
2. This should not be an issue once 1. is addressed.

== Address mappings ==
1. Probably won't address this, it's readable enough.
2. Yes, it means every entry in the memory map, regardless of type, will be mapped. The first 4GiB are a result of an early legacy decision. Early on in the development of the stivale standards only 4GiB of memory were mapped, and memory map entries were not relevant. This was done because it usually causes, at least on legacy systems without MMIO remapping above 4GiB, most of the important MMIO regions to be mapped, including important stuff like xAPIC MMIO.
3. The rationale is that the -2GiB area is not relevant for anything but mapping of the kernel's segments. There is very little reason why you'd want to access the first 2GiB of the address space at `0xffffffff80000000` rather than at the direct map at `9xffff800000000000` (or `0xff00000000000000`). The lack of a direct map at -2GiB with PMRs on helps catch possible segmentation faults while accessing the kernel's data/rodata sections, for example, which could just silently fail if everything was mapped.

== Other kernel entry notes ==
1. Possible future expansion. Limine does not use these entries but reserving them for a hypothetical implementation that needs to run 16 bit code certainly does not harm.
2. Yes that is true. This is more of a "semantic" distinction than a CPU-dictated constraint. The 64-bit data GDT descriptor is the descriptor used by the bootloader when running 64-bit code, which can be identical to a 32-bit data descriptor.
3. No, it doesn't. The mere presence of these entries in the GDT does not preclude an OS from running on a IA-32 only system, as long as no attempt is ever made at loading said entries (and, for example, 32-bit BIOS Limine never does that).
4. No, it is not. Obviously if RSP is 0, the kernel is expected to set up a stack itself, thus pushing anything on an invalid stack (in this case the return address) makes no sense.
5. Yes, they are exited, this will be addressed.

== Stivale2 header ==
This means there *either* is an ELF section called .stivale2hdr, containing the header, *or* there is an anchor pointing to said header. Wording is a bit bad, I agree, this will be addressed.
1. The anchor points to the header, which can reside anywhere else. After that, the header works the same as it would if it is found in a .stivale2hdr section.
2. The idea was that unrecognised flags would be ignored by the bootloader and it is the kernel's responsibility to detect this. This should be better addressed, too.

== PMRs ==
1. PMRs only make sense if paging is enabled. Since 32-bit kernels' machine state involves paging being disabled, this is the rationale.
2. Yes this can be better addressed.

== Header tags ==
You raise a very compelling point here, lack of support for a header tag should never result in refusal to boot, any such part of the spec is conflicting with the nature of the spec itself and should be rectified.
There won't be a set of mandatory tag, just anything involving the bootloader absolutely refusing to boot by spec on certain header tags properties should either be stripped or specified that boot refusal will occur only *if* the tag is supported at all.

== Terminal tag ==
Some missing parts of the spec are only missing because they are added as they are implemented in the reference implementation (Limine). Any change to the spec must be backwards compatible, and if your bootloader happens to provide terminal support for IA-32 kernels then this part of the specification can be added. Just like ARM parts of the specification were added as Sabaton added support for them.

== High memory mapping tag ==
Correct. Limine does not create this tag as it is more useful on ARM where that value is not specified to be as set in stone as it is on x86. (See ARM machine state).

== Conclusion ==
Thanks for raising these points, feedback is always very appreciated. I will work on addressing the issues I mentioned as to be addressed in this comment.

If there is still any confusion after this answer please let me know.

**Comment by davmac314** [comment]
Thanks, that really clears everything up!

I had thought `stack` of 0 in the header meant the bootloader would provide a stack (or at least not set a specific stack), rather than that RSP would literally be 0, but I think that's my own mis-reading rather than a fault in the spec.
